; Configurações padrão do Jybóia IDE 2.0

[general]
ui_mode = regular
language = pt_BR
single_instance = False

[run]
allow_running_unnamed_programs = False
auto_save_unnamed_as_unsaved = True
auto_cd = True
warn_module_shadowing = True
